# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: pet
resources:
  pet:index:RandomName:
    isComponent: true
    inputProperties:
      numParts:
        type: number
        description: Number of parts to pet name.
    requiredInputs:
      - numParts
    properties:
      petName:
        type: string
        description: The generated pet name.
    required:
      - petName 
language:
  csharp:
    packageReferences:
      Pulumi: 3.*
      Pulumi.Random: 4.*
  go:
    generateResourceContainerTypes: true
    importBasePath: github.com/mitch/pulumi-pet/sdk/go/pet
  nodejs:
    dependencies:
      "@pulumi/random": "^4.0.0"
    devDependencies:
      typescript: "^3.7.0"
  python:
    requires:
      pulumi: ">=3.0.0,<4.0.0"
      pulumi-random: ">=4.0.0,<5.0.0"
