// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class RandomName extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'pet:index:RandomName';

    /**
     * Returns true if the given object is an instance of RandomName.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RandomName {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RandomName.__pulumiType;
    }

    /**
     * The generated pet name.
     */
    public /*out*/ readonly petName!: pulumi.Output<string>;

    /**
     * Create a RandomName resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RandomNameArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.numParts === undefined) && !opts.urn) {
                throw new Error("Missing required property 'numParts'");
            }
            resourceInputs["numParts"] = args ? args.numParts : undefined;
            resourceInputs["petName"] = undefined /*out*/;
        } else {
            resourceInputs["petName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RandomName.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a RandomName resource.
 */
export interface RandomNameArgs {
    /**
     * Number of parts to pet name.
     */
    numParts: pulumi.Input<number>;
}
